//! With the `generate-bindings` feature, regenerates `src/bindings.rs` from the vendored
//! `duckdb_extension_v2.h`. Without it, the checked-in bindings are used as they are, so a normal
//! build needs no libclang.

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    #[cfg(feature = "generate-bindings")]
    generate();
}

#[cfg(feature = "generate-bindings")]
fn generate() {
    use std::path::PathBuf;

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let vendor = manifest_dir.join("vendor");
    println!("cargo::rerun-if-changed={}", vendor.display());

    let bindings = bindgen::Builder::default()
        .header(vendor.join("duckdb_extension_v2.h").to_str().unwrap())
        .clang_arg(format!("-I{}", vendor.display()))
        // Pin the C API version the extension targets; the loader refuses newer versions.
        .clang_arg("-DDUCKDB_EXTENSION_API_VERSION_MAJOR=2")
        .clang_arg("-DDUCKDB_EXTENSION_API_VERSION_MINOR=0")
        .clang_arg("-DDUCKDB_EXTENSION_API_VERSION_PATCH=0")
        // Types, constants and the function-pointer table only. The free functions declared in
        // duckdb_v2.h are for programs linking libduckdb; a loadable extension calls through the
        // table that `get_api` returns, since the host exports no `duckdb_*` symbols.
        .allowlist_type("duckdb_.*|DUCKDB_.*|idx_t")
        .allowlist_var("DUCKDB_.*")
        .default_enum_style(bindgen::EnumVariation::Consts)
        .prepend_enum_name(false)
        .generate_comments(true)
        .derive_default(true)
        .layout_tests(true)
        .raw_line("// Generated by bindgen from vendor/duckdb_extension_v2.h; regenerate with `make bindings`.")
        .generate()
        .expect("bindgen failed on duckdb_extension_v2.h");
    bindings
        .write_to_file(manifest_dir.join("src/bindings.rs"))
        .expect("writing src/bindings.rs");
}
